/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package net_sports_management.GUI;

import javax.swing.JOptionPane;

/**
 *
 * @author nk
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        setTitle("ADMIN DASHBOARD .");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDepartments = new javax.swing.JButton();
        btnTeams = new javax.swing.JButton();
        btnPlayers = new javax.swing.JButton();
        btnTournaments = new javax.swing.JButton();
        btnSchedules = new javax.swing.JButton();
        btnResults = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDepartments.setBackground(new java.awt.Color(204, 204, 204));
        btnDepartments.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDepartments.setText("Departments");
        btnDepartments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepartmentsActionPerformed(evt);
            }
        });
        getContentPane().add(btnDepartments, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 49, -1, 40));

        btnTeams.setBackground(new java.awt.Color(204, 204, 204));
        btnTeams.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTeams.setText("Teams");
        btnTeams.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTeamsActionPerformed(evt);
            }
        });
        getContentPane().add(btnTeams, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 209, 110, 40));

        btnPlayers.setBackground(new java.awt.Color(204, 204, 204));
        btnPlayers.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPlayers.setText("Players");
        btnPlayers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayersActionPerformed(evt);
            }
        });
        getContentPane().add(btnPlayers, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 125, 110, 40));

        btnTournaments.setBackground(new java.awt.Color(204, 204, 204));
        btnTournaments.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTournaments.setText("Tournaments");
        btnTournaments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTournamentsActionPerformed(evt);
            }
        });
        getContentPane().add(btnTournaments, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 49, -1, 40));

        btnSchedules.setBackground(new java.awt.Color(204, 204, 204));
        btnSchedules.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSchedules.setText("Schedules");
        btnSchedules.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSchedulesActionPerformed(evt);
            }
        });
        getContentPane().add(btnSchedules, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 125, 120, 40));

        btnResults.setBackground(new java.awt.Color(204, 204, 204));
        btnResults.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnResults.setText("Results");
        btnResults.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResultsActionPerformed(evt);
            }
        });
        getContentPane().add(btnResults, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 209, 120, 40));

        btnLogout.setBackground(new java.awt.Color(204, 204, 204));
        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 285, 280, 30));

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pngaaa.com-3103927.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 370));

        jPanel1.setBackground(new java.awt.Color(239, 228, 229));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDepartmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepartmentsActionPerformed
DepartmentManagement dm = new DepartmentManagement();
    dm.setVisible(true);
    this.dispose();         
    }//GEN-LAST:event_btnDepartmentsActionPerformed

    private void btnTeamsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTeamsActionPerformed
            TeamManagement tm = new     TeamManagement();
            tm.setVisible(true);
            this.dispose();

    }//GEN-LAST:event_btnTeamsActionPerformed

    private void btnPlayersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayersActionPerformed
      PlayerManagement pm = new PlayerManagement();
      pm.setVisible(true);
            this.dispose();
        
    }//GEN-LAST:event_btnPlayersActionPerformed

    private void btnTournamentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTournamentsActionPerformed
        TournamentManagement tm1 =new TournamentManagement();
        tm1.setVisible(true);
            this.dispose();
        
    }//GEN-LAST:event_btnTournamentsActionPerformed

    private void btnSchedulesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSchedulesActionPerformed
       ScheduleManagement s =new ScheduleManagement();
        s.setVisible(true);
            this.dispose();
        
    }//GEN-LAST:event_btnSchedulesActionPerformed

    private void btnResultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResultsActionPerformed
            ResultsManagement r =new ResultsManagement();
        r.setVisible(true);
            this.dispose();

    }//GEN-LAST:event_btnResultsActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
             int confirm = JOptionPane.showConfirmDialog(
        this,
        "Are you sure you want to logout?",
        "Logout",
        JOptionPane.YES_NO_OPTION
    );

    if (confirm == JOptionPane.YES_OPTION) {

        LoginForm login = new LoginForm();
        login.setVisible(true);

        this.dispose();
    }

        
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDepartments;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPlayers;
    private javax.swing.JButton btnResults;
    private javax.swing.JButton btnSchedules;
    private javax.swing.JButton btnTeams;
    private javax.swing.JButton btnTournaments;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
