/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package net_sports_management.GUI;

import dao.ResultDAO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nk
 */
public class ResultsManagement extends javax.swing.JFrame {

    /**
     * Creates new form ResultsManagement
     */
    public ResultsManagement() {
        initComponents();
        btnUpdate.setEnabled(false);
        setTitle("RESULT  Management System");
                        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

addWindowListener(new java.awt.event.WindowAdapter() {
    @Override
    public void windowClosing(java.awt.event.WindowEvent e) {

        javax.swing.JOptionPane.showMessageDialog(
            null,
            "Please use BACK button to go back"
        );
    }
});
        loadData();       //FROM DAO
    refreshTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbTournament = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmbWinner = new javax.swing.JComboBox<>();
        cmbLooser = new javax.swing.JComboBox<>();
        btnSubmit = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        txtId.setEditable(false);
        txtId.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        jLabel1.setText("ID :-");

        jLabel2.setText("WinnerTeam Name :-");

        jLabel3.setText("Tournament Name :-");

        jLabel5.setText("LooserTeam Name :-");

        btnSubmit.setText("SUBMIT");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnRefresh.setText("REFRESH");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnClear.setText("CLEAR");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Sr.No", "ID", "Tournament Name", "Winner Team", "Looser Team"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbTournament, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmbLooser, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnSubmit)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnUpdate)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnDelete)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnRefresh)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(btnClear)
                                        .addGap(69, 69, 69)))
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbWinner, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(cmbTournament, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbWinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbLooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubmit)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete)
                    .addComponent(btnRefresh)
                    .addComponent(btnClear)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
          model.Tournament tr = (model.Tournament) cmbTournament.getSelectedItem();
    model.Team winner = (model.Team) cmbWinner.getSelectedItem();
    model.Team loser = (model.Team) cmbLooser.getSelectedItem();

    // VALIDATION

    if (tr == null) {
        JOptionPane.showMessageDialog(this, "Select Tournament");
        return;
    }

    if (winner == null) {
        JOptionPane.showMessageDialog(this, "Select Winner Team");
        return;
    }

    if (loser == null) {
        JOptionPane.showMessageDialog(this, "Select Loser Team");
        return;
    }

    if (winner.getId() == loser.getId()) {
        JOptionPane.showMessageDialog(this, "Winner and Loser cannot be same");
        return;
    }

    // CREATE OBJECT
    model.Result r = new model.Result(
        tr.getId(),
        winner.getId(),
        loser.getId()
    );

    new dao.ResultDAO().addResult(r);

    JOptionPane.showMessageDialog(this, "Result Added Successfully");

    refreshTable();
    clearFields();
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
       model.Tournament tr = (model.Tournament) cmbTournament.getSelectedItem();
    model.Team winner = (model.Team) cmbWinner.getSelectedItem();
    model.Team loser = (model.Team) cmbLooser.getSelectedItem();

    // VALIDATION

    if (tr == null) {
        JOptionPane.showMessageDialog(this, "Select Tournament");
        return;
    }

    if (winner == null) {
        JOptionPane.showMessageDialog(this, "Select Winner Team");
        return;
    }

    if (loser == null) {
        JOptionPane.showMessageDialog(this, "Select Loser Team");
        return;
    }

    if (winner.getId() == loser.getId()) {
        JOptionPane.showMessageDialog(this, "Winner and Loser cannot be same");
        return;
    }

    //  CREATE OBJECT
    model.Result r = new model.Result(
        tr.getId(),
        winner.getId(),
        loser.getId()
    );

    new dao.ResultDAO().addResult(r);

    JOptionPane.showMessageDialog(this, "Result Added Successfully");

    refreshTable();
    clearFields();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
  int row = table.getSelectedRow();

    if (row == -1) return;

    txtId.setText(table.getValueAt(row, 1).toString());

    String tournamentName = table.getValueAt(row, 2).toString();
    String winnerName = table.getValueAt(row, 3).toString();
    String looserName = table.getValueAt(row, 4).toString();

    //  Tournament
    for (int i = 0; i < cmbTournament.getItemCount(); i++) {
        model.Tournament t = cmbTournament.getItemAt(i);
        if (t.getTournamentName().equals(tournamentName)) {
            cmbTournament.setSelectedIndex(i);
            break;
        }
    }

    //  Winner
    for (int i = 0; i < cmbWinner.getItemCount(); i++) {
        model.Team t = cmbWinner.getItemAt(i);
        if (t.getTeamName().equals(winnerName)) {
            cmbWinner.setSelectedIndex(i);
            break;
        }
    }

    //  LOSER 
    for (int i = 0; i < cmbLooser.getItemCount(); i++) {
        model.Team t = cmbLooser.getItemAt(i);
        if (t.getTeamName().equals(looserName)) {
            cmbLooser.setSelectedIndex(i);
            break;
        }
    }  
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
         refreshTable();
        
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clearFields();// TODO add your handling code here:
    }//GEN-LAST:event_btnClearActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Dashboard dashboard = new Dashboard();
        dashboard.setVisible(true);

        this.dispose();       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
                  int row = table.getSelectedRow();

    if (row == -1) return;
                    btnSubmit.setEnabled(false);
        btnUpdate.setEnabled(true);
    txtId.setText(table.getValueAt(row, 1).toString());

    String tournamentName = table.getValueAt(row, 2).toString();
    String winnerName = table.getValueAt(row, 3).toString();
    String looserName = table.getValueAt(row, 4).toString();

    //  Tournament
    for (int i = 0; i < cmbTournament.getItemCount(); i++) {
        model.Tournament t = cmbTournament.getItemAt(i);
        if (t.getTournamentName().equals(tournamentName)) {
            cmbTournament.setSelectedIndex(i);
            break;
        }
    }

    //  Winner
    for (int i = 0; i < cmbWinner.getItemCount(); i++) {
        model.Team t = cmbWinner.getItemAt(i);
        if (t.getTeamName().equals(winnerName)) {
            cmbWinner.setSelectedIndex(i);
            break;
        }
    }

    //  LoOSER 
    for (int i = 0; i < cmbLooser.getItemCount(); i++) {
        model.Team t = cmbLooser.getItemAt(i);
        if (t.getTeamName().equals(looserName)) {
            cmbLooser.setSelectedIndex(i);
            break;
        }
    }  
    }//GEN-LAST:event_tableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResultsManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResultsManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResultsManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResultsManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResultsManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<model.Team> cmbLooser;
    private javax.swing.JComboBox<model.Tournament> cmbTournament;
    private javax.swing.JComboBox<model.Team> cmbWinner;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables
        private void loadData() {

    cmbTournament.removeAllItems();
    cmbWinner.removeAllItems();
    cmbLooser.removeAllItems();

    // Tournament
    for (model.Tournament t : new dao.TournamentDAO().getAllTournamentObjects()) {
        cmbTournament.addItem(t);
    }

    // Teams
    for (model.Team t : new dao.TeamDAO().getAllTeamObjects()) {
        cmbWinner.addItem(t);
        cmbLooser.addItem(t);
    }
}
    
    
    private void clearFields() {
        btnSubmit.setEnabled(true);
        btnUpdate.setEnabled(true);
         txtId.setText("");

    if (cmbTournament.getItemCount() > 0)
        cmbTournament.setSelectedIndex(0);

    if (cmbWinner.getItemCount() > 0)
        cmbWinner.setSelectedIndex(0);

    if (cmbLooser.getItemCount() > 0)
        cmbLooser.setSelectedIndex(0);
    }

    private void refreshTable() {
         DefaultTableModel model = (DefaultTableModel) table.getModel();
    model.setRowCount(0);

    List<Object[]> list = new dao.ResultDAO().getAllResults();

    int count = 1;

    for (Object[] row : list) {

        model.addRow(new Object[]{
            count++,
            row[0], // ID
            row[1], // Tournament
            row[2], // Winner
            row[3]  // Loser
        });
    }
    }
}
