package net_sports_management.GUI;

import com.toedter.calendar.JDateChooser;
import dao.TeamDAO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Tournament;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author nk
 */
public class ScheduleManagement extends javax.swing.JFrame {
    
    

    /**
     * Creates new form ScheduleManagement
     */
    public ScheduleManagement() {
        initComponents();
        
                btnUpdate.setEnabled(false);
                setTitle("SCHEDULE Management System");
                setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

addWindowListener(new java.awt.event.WindowAdapter() {
    @Override
    public void windowClosing(java.awt.event.WindowEvent e) {

        javax.swing.JOptionPane.showMessageDialog(
            null,
            "Please use BACK button to go back"
        );
    }
});
        
         txtId.setEditable(false);
    txtId.setBackground(new java.awt.Color(220,220,220));

    btnClear.addActionListener(e -> clearFields());

    loadTeams();        
    loadTournaments();  
    loadDepartments();  

    refreshTable();
    }
    
    
    private void loadTeams() {
    cmbTeam.removeAllItems();

    for (model.Team t : new dao.TeamDAO().getAllTeamObjects()) {
    cmbTeam.addItem(t);
}
}
    
    
    private void loadTournaments() {
    cmbTournament.removeAllItems();

    for (model.Tournament t : new dao.TournamentDAO().getAllTournamentObjects()) {
    cmbTournament.addItem(t);
}
}
    
    private void loadDepartments() {
    cmbDepartment.removeAllItems();

    for (model.Department d : new dao.DepartmentDAO().getAllDepartments()) {
        cmbDepartment.addItem(d);   //  object
    }
}
    
        private String getDate() {
    if (jDateChooser.getDate() == null) return null;

    return new java.text.SimpleDateFormat("yyyy-MM-dd")
            .format(jDateChooser.getDate());
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        txtId = new javax.swing.JTextField();
        cmbTeam = new javax.swing.JComboBox<>();
        cmbTournament = new javax.swing.JComboBox<>();
        cmbDepartment = new javax.swing.JComboBox<>();
        txtLocation = new javax.swing.JTextField();
        jDateChooser = new com.toedter.calendar.JDateChooser();
        btnSubmit = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        search = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Sr.NO.", "TeamID", "Team Name", "Department", "Coach"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        txtId.setEditable(false);
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        cmbTeam.setModel(new javax.swing.DefaultComboBoxModel<>());
        cmbTeam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbTeamMouseClicked(evt);
            }
        });
        cmbTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTeamActionPerformed(evt);
            }
        });

        cmbTeam.setModel(new javax.swing.DefaultComboBoxModel<>());
        cmbTournament.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbTournamentMouseClicked(evt);
            }
        });
        cmbTournament.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTournamentActionPerformed(evt);
            }
        });

        cmbTeam.setModel(new javax.swing.DefaultComboBoxModel<>());
        cmbDepartment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbDepartmentMouseClicked(evt);
            }
        });
        cmbDepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDepartmentActionPerformed(evt);
            }
        });

        btnSubmit.setText("SUBMIT");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnClear.setText("CLEAR");

        btnRefresh.setText("REFRESH");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        search.setToolTipText("Search");

        btnSearch.setText("SEARCH");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Sr.NO.", "id", "Team Name", "Tournament Name", "Department", "Location", "Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, true, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table1);

        jLabel1.setText("S. ID :-");

        jLabel2.setText("TEAM NAME : -");

        jLabel3.setText("TOURNAMENT NAME :-");

        jLabel4.setText("DEPARTMENT NAME :-");

        jLabel5.setText("LOCATION :-");

        jLabel6.setText("MATCH   SCHEDULED  ON DATE :-");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtLocation, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmbDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbTeam, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(13, 13, 13)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbTournament, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSubmit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnUpdate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDelete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnClear)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRefresh))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
                            .addComponent(jDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbTournament, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(cmbTeam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtLocation, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSubmit)
                            .addComponent(btnUpdate)
                            .addComponent(btnDelete)
                            .addComponent(btnClear)
                            .addComponent(btnRefresh)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSearch)
                            .addComponent(jButton1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void cmbTeamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbTeamMouseClicked

    }//GEN-LAST:event_cmbTeamMouseClicked

    private void cmbTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTeamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTeamActionPerformed

    private void cmbTournamentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbTournamentMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTournamentMouseClicked

    private void cmbTournamentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTournamentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTournamentActionPerformed

    private void cmbDepartmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbDepartmentMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbDepartmentMouseClicked

    private void cmbDepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDepartmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbDepartmentActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
         model.Team team = (model.Team) cmbTeam.getSelectedItem();
    model.Tournament t = (model.Tournament) cmbTournament.getSelectedItem();
    model.Department d = (model.Department) cmbDepartment.getSelectedItem();

    String location = txtLocation.getText().trim();
            if (!txtId.getText().trim().isEmpty()) {
    JOptionPane.showMessageDialog(this, "Use UPDATE instead of SUBMIT for existing record!");
    return;
}

    if (team == null) {
        JOptionPane.showMessageDialog(this, "Select Team");
        return;
    }

    if (t == null) {
        JOptionPane.showMessageDialog(this, "Select Tournament");
        return;
    }

    if (d == null) {
        JOptionPane.showMessageDialog(this, "Select Department");
        return;
    }

    if (location.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Enter Location");
        return;
    }

   if (jDateChooser.getDate() == null) {
    JOptionPane.showMessageDialog(this, "Select Date");
    return;
}

    // 🔹 CREATE OBJECT
   model.Schedule s = new model.Schedule(
    team.getId(),
    t.getId(),
    d.getId(),
    location,
    getDate()   
);

    // 🔹 SAVE
    new dao.ScheduleDAO().addSchedule(s);

    JOptionPane.showMessageDialog(this, "Schedule Added Successfully");

    refreshTable();
    clearFields();
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
                                           
         

    int id = Integer.parseInt(txtId.getText());

    model.Team team = (model.Team) cmbTeam.getSelectedItem();
    model.Tournament t = (model.Tournament) cmbTournament.getSelectedItem();
    model.Department d = (model.Department) cmbDepartment.getSelectedItem();

    if (team == null || t == null || d == null) {
        JOptionPane.showMessageDialog(this, "Select all fields!");
        return;
    }

    if (txtLocation.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Location is required!");
        return;
    }

    model.Schedule s = new model.Schedule(
        id,   // ✅ ID comes from selected row
        team.getId(),
        t.getId(),
        d.getId(),
        txtLocation.getText(),
        getDate()
    );

    new dao.ScheduleDAO().updateSchedule(s);

    JOptionPane.showMessageDialog(this, "Updated Successfully ✅");

    refreshTable();
    clearFields();
                              
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed

         if (txtId.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Select row first!");
        return;
    }

    int id = Integer.parseInt(txtId.getText());

    new dao.ScheduleDAO().deleteSchedule(id);

    JOptionPane.showMessageDialog(this, "Deleted Successfully");

    refreshTable();
    clearFields();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        refreshTable();
        
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String text = search.getText().toLowerCase();

        DefaultTableModel model = (DefaultTableModel) table1.getModel();
        model.setRowCount(0);

        List<Object[]> list = new dao.ScheduleDAO().getAllSchedules();

        int count = 1;

        for (Object[] row : list) {

            if (row[1].toString().toLowerCase().contains(text) ||
                row[2].toString().toLowerCase().contains(text) ||
                row[3].toString().toLowerCase().contains(text)) {

                model.addRow(new Object[]{
                    count++,
                    row[0], // ID
                    row[1], // Team
                    row[2], // Tournament
                    row[3], // Department
                    row[4], // Location
                    row[5]  // Date
                });
            }
        } 
    }//GEN-LAST:event_btnSearchActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Dashboard dashboard = new Dashboard();
        dashboard.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        
    }//GEN-LAST:event_tableMouseClicked

    private void table1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table1MouseClicked
            int row = table1.getSelectedRow();
                btnSubmit.setEnabled(false);
        btnUpdate.setEnabled(true);
    if (row == -1) return;

    // ✅ Safe getter
    Object idObj = table1.getValueAt(row, 1);
    Object teamObj = table1.getValueAt(row, 2);
    Object tournamentObj = table1.getValueAt(row, 3);
    Object deptObj = table1.getValueAt(row, 4);
    Object locationObj = table1.getValueAt(row, 5);
    Object dateObj = table1.getValueAt(row, 6);

    // 🔴 NULL CHECK
    if (idObj == null) {
        JOptionPane.showMessageDialog(this, "Invalid row selected!");
        return;
    }

    txtId.setText(idObj.toString());
    txtLocation.setText(locationObj != null ? locationObj.toString() : "");

    String teamName = (teamObj != null) ? teamObj.toString() : "";
    String tournamentName = (tournamentObj != null) ? tournamentObj.toString() : "";
    String deptName = (deptObj != null) ? deptObj.toString() : "";

    // ✅ Set ComboBoxes safely
    for (int i = 0; i < cmbTeam.getItemCount(); i++) {
        if (cmbTeam.getItemAt(i).toString().equals(teamName)) {
            cmbTeam.setSelectedIndex(i);
            break;
        }
    }

    for (int i = 0; i < cmbTournament.getItemCount(); i++) {
        if (cmbTournament.getItemAt(i).toString().equals(tournamentName)) {
            cmbTournament.setSelectedIndex(i);
            break;
        }
    }

    for (int i = 0; i < cmbDepartment.getItemCount(); i++) {
        if (cmbDepartment.getItemAt(i).toString().equals(deptName)) {
            cmbDepartment.setSelectedIndex(i);
            break;
        }
    }

    // ✅ Date safe parse
    if (dateObj != null) {
        try {
            java.util.Date d = new java.text.SimpleDateFormat("yyyy-MM-dd")
                    .parse(dateObj.toString());
            jDateChooser.setDate(d);
        } catch (Exception e) {
            jDateChooser.setDate(null);
        }
    } else {
        jDateChooser.setDate(null);
    }
    }//GEN-LAST:event_table1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScheduleManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScheduleManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScheduleManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScheduleManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScheduleManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<model.Department> cmbDepartment;
    private javax.swing.JComboBox<model.Team> cmbTeam;
    private javax.swing.JComboBox<model.Tournament> cmbTournament;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField search;
    private javax.swing.JTable table;
    private javax.swing.JTable table1;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtLocation;
    // End of variables declaration//GEN-END:variables
private void refreshTable() {

    DefaultTableModel model = (DefaultTableModel) table1.getModel();
    model.setRowCount(0);

    List<Object[]> list = new dao.ScheduleDAO().getAllSchedules();

    int count = 1;

    for (Object[] row : list) {

        model.addRow(new Object[]{
            count++,
            row[0],  // ID
            row[1],  // Team Name
            row[2],  // Tournament Name
            row[3],  // Dept Head
            row[4],  // Location
            row[5]   // Date
        });

    }
}


private void clearFields() {
    btnSubmit.setEnabled(true);
        btnUpdate.setEnabled(true);
    txtId.setText("");
    txtLocation.setText("");
    jDateChooser.setDate(null);

    if (cmbTeam.getItemCount() > 0) cmbTeam.setSelectedIndex(0);
    if (cmbTournament.getItemCount() > 0) cmbTournament.setSelectedIndex(0);
    if (cmbDepartment.getItemCount() > 0) cmbDepartment.setSelectedIndex(0);
}

}
