/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package net_sports_management.GUI;

import dao.CoachDAO;
import dao.DepartmentDAO;
import dao.TeamDAO;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Coach;
import model.Department;
import model.Team;

/**
 *
 * @author nk
 */
public class TeamManagement extends javax.swing.JFrame {

    /**
     * Creates new form TeamManagement
     */
    public TeamManagement() {
        initComponents();
        setTitle("TEAM  Management System");
        btnUpdate.setEnabled(false);
        btnClear.addActionListener(evt -> clearFields());
        txtId.setEditable(false);
        txtId.setBackground(new java.awt.Color(220,220,220));
        cmbCoach.setModel(new DefaultComboBoxModel<>());
         cmbDepartment.setModel(new DefaultComboBoxModel<>());
         
         
         
                            setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

addWindowListener(new java.awt.event.WindowAdapter() {
    @Override
    public void windowClosing(java.awt.event.WindowEvent e) {

        javax.swing.JOptionPane.showMessageDialog(
            null,
            "Please use BACK button to go back"
        );
    }
});

    loadCoaches();
    loadDepartments();  //  IMPORTANT
    refreshTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        teamName = new javax.swing.JTextField();
        cmbDepartment = new javax.swing.JComboBox<>();
        btnSubmit = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        search = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        cmbCoach = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Team ID:-");

        jLabel2.setText("Team Name :-");

        jLabel3.setText(" Coach :-");

        txtId.setEditable(false);

        cmbDepartment.setModel(new javax.swing.DefaultComboBoxModel<>());
        cmbDepartment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbDepartmentMouseClicked(evt);
            }
        });
        cmbDepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDepartmentActionPerformed(evt);
            }
        });

        btnSubmit.setText("SUBMIT");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnClear.setText("CLEAR");

        btnRefresh.setText("REFRESH");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnSearch.setText("SEARCH");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        search.setToolTipText("Search");

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Sr.NO.", "TeamID", "Team Name", "Department", "Coach"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cmbCoach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbCoachMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbCoach, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(teamName)
                            .addComponent(cmbDepartment, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSubmit)
                        .addGap(23, 23, 23)
                        .addComponent(btnUpdate)
                        .addGap(0, 61, Short.MAX_VALUE)
                        .addComponent(btnDelete)
                        .addGap(18, 18, 18)
                        .addComponent(btnClear)
                        .addGap(26, 26, 26)
                        .addComponent(btnRefresh)
                        .addGap(65, 65, 65)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(search)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(teamName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbCoach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubmit)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete)
                    .addComponent(btnClear)
                    .addComponent(btnRefresh)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearch)
                    .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbDepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDepartmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbDepartmentActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
                    String name = teamName.getText().trim();
    Department dept = (Department) cmbDepartment.getSelectedItem();
    Coach coach = (Coach) cmbCoach.getSelectedItem();
    
    

    // 🔴 VALIDATION
    if (name.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Enter Team Name");
        return;
    }

    if (dept == null) {
        JOptionPane.showMessageDialog(this, "Select Department");
        return;
    }

    if (coach == null) {
        JOptionPane.showMessageDialog(this, "Select Coach");
        return;
    }

    // 🔹 CREATE OBJECT
    Team t = new Team(name, dept.getId(), coach.getId());

    new TeamDAO().addTeam(t);

    JOptionPane.showMessageDialog(this, "Team Added Successfully");

    refreshTable();
    clearFields();  // TODO add your handling code here:
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
                   String idText = txtId.getText().trim();
    String name = teamName.getText().trim();
    Department dept = (Department) cmbDepartment.getSelectedItem();
    Coach coach = (Coach) cmbCoach.getSelectedItem();

    if (idText.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Select a team to update!");
        return;
    }

    if (name.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Enter Team Name");
        return;
    }

    if (dept == null) {
        JOptionPane.showMessageDialog(this, "Select Department");
        return;
    }

    if (coach == null) {
        JOptionPane.showMessageDialog(this, "Select Coach");
        return;
    }

    int id = Integer.parseInt(idText);

    Team t = new Team(id, name, dept.getId(), coach.getId()); // ✅ include ID

    new TeamDAO().updateTeam(t); // ✅ correct method

    JOptionPane.showMessageDialog(this, "Team Updated Successfully");

    refreshTable();
    clearFields();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
            
    int row = table.getSelectedRow();

        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Select row first");
            return;
        }

        int id = Integer.parseInt(table.getValueAt(row, 1).toString());

        new TeamDAO().deleteTeam(id);

        JOptionPane.showMessageDialog(this, "Team Deleted"); // ⭐ ADDED

        refreshTable();
        clearFields();    // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
       refreshTable();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        btnSubmit.setEnabled(false);
        btnUpdate.setEnabled(true);
        int row = table.getSelectedRow();

    if (row == -1) return;

    //  Set basic fields
    txtId.setText(table.getValueAt(row, 1).toString());
    teamName.setText(table.getValueAt(row, 2).toString());

    //  Department selection
    String deptName = table.getValueAt(row, 3).toString();

    for (int i = 0; i < cmbDepartment.getItemCount(); i++) {
        Department d = (Department) cmbDepartment.getItemAt(i);
        if (d.toString().equals(deptName)) {
            cmbDepartment.setSelectedIndex(i);
            break;
        }
    }

    //  Coach selection
    String coachName = table.getValueAt(row, 4).toString();

    for (int i = 0; i < cmbCoach.getItemCount(); i++) {
        Coach c = (Coach) cmbCoach.getItemAt(i);
        if (c.getName().equals(coachName)) {
            cmbCoach.setSelectedIndex(i);
            break;
        }
    }
    }//GEN-LAST:event_tableMouseClicked

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
                  String text = search.getText().toLowerCase();

    DefaultTableModel model = (DefaultTableModel) table.getModel();
    model.setRowCount(0);

    List<Object[]> list = new TeamDAO().getAllTeams(); //  correct

    int count = 1;

    for (Object[] row : list) {

        if (row[1].toString().toLowerCase().contains(text) ||
            row[2].toString().toLowerCase().contains(text) ||
            row[3].toString().toLowerCase().contains(text)) {

            model.addRow(new Object[]{
                count++,
                row[0], // ID
                row[1], // Name
                row[2], // Department
                row[3]  // Coach
            });
        }
    } 
    }//GEN-LAST:event_btnSearchActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         Dashboard dashboard = new Dashboard();
    dashboard.setVisible(true);
    this.dispose(); //        // TODO add your        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cmbCoachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbCoachMouseClicked

// TODO add your handling code here:
    }//GEN-LAST:event_cmbCoachMouseClicked

    private void cmbDepartmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbDepartmentMouseClicked
    }//GEN-LAST:event_cmbDepartmentMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeamManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeamManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeamManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeamManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TeamManagement().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<model.Coach> cmbCoach;
    private javax.swing.JComboBox<model.Department> cmbDepartment;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField search;
    private javax.swing.JTable table;
    private javax.swing.JTextField teamName;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables

    private void loadDepartments() {
     DepartmentDAO dao = new DepartmentDAO();
        List<Department> list = dao.getAllDepartments();

        cmbDepartment.removeAllItems();

        for (Department d : list) {
            cmbDepartment.addItem(d);
        }
}
  

    private void refreshTable() {
         DefaultTableModel model = (DefaultTableModel) table.getModel();
    model.setRowCount(0); // clear table

    TeamDAO dao = new TeamDAO();
    List<Object[]> list = dao.getAllTeams();  // from DAO

    int srNo = 1;

    for (Object[] row : list) {

        model.addRow(new Object[]{
            srNo++,        // Sr No
            row[0],        // Id
            row[1],        // Name
            row[2],        // DeptHead  
            row[3]         // Coach
        });
    }
    }

    private void clearFields() {
        btnSubmit.setEnabled(true);
        btnUpdate.setEnabled(true);
       
      txtId.setText("");
        teamName.setText("");
        if (cmbCoach.getItemCount() > 0) {
    cmbCoach.setSelectedIndex(0);
}
        if (cmbDepartment.getItemCount() > 0) {
            cmbDepartment.setSelectedIndex(0);
        }
    }

    private void loadCoaches() {
    CoachDAO dao = new CoachDAO();
    List<Coach> list = dao.getAllCoaches();

    cmbCoach.removeAllItems();

    for (Coach c : list) {
        cmbCoach.addItem(c);
    }    
    }

   
}
